Feature/kafka
cichan02/authentication-service pull request #4
Opened 2023-03-17 11:12 UTC by cichan02

2023-03-17 11:41 UTC, h1alexbel requested changes

2023-03-17 11:41 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/service/impl/UserServiceImpl.java
> +    private final RestTemplate restTemplate;
why it's a rest template? We are using project reactor, so use webclient instead

2023-03-17 11:41 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/service/impl/EmailServiceImpl.java
> +                                "key",
key shouldn't be hardcoded, consider object id or something else

2023-03-17 11:41 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/service/JwtService.java
> +    Mono<String> extractUsername(String jwt);
I see no reason to use `Mono` or other publishers here. It's better to use Strings and Boolean, like it was before

2023-03-20 10:22 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/service/impl/EmailServiceImpl.java
> +                                "key",
add uuid to events

2023-03-20 12:00 UTC, h1alexbel requested changes

2023-03-20 12:00 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/service/impl/UserServiceImpl.java
> +                .block();
don't block publisher

2023-03-20 12:00 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/service/impl/UserServiceImpl.java
> +                .block();
don't block publisher

2023-03-20 12:08 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/config/XMLConfig.java
> +        return new XMLDocument(new File("/Users/solvd/IdeaProjects/micro-airport/authentication-service/src/main/resources/kafka/producer.xml"));
Yes, i know.
But none of that works:
/kafka/producer.xml
kafka/producer.xml
/src/main/resources/kafka/producer.xml
src/main/resources/kafka/producer.xml

2023-03-20 12:12 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/config/XMLConfig.java
> +        return new XMLDocument(new File("/Users/solvd/IdeaProjects/micro-airport/authentication-service/src/main/resources/kafka/producer.xml"));
@cichan02 fix it please

2023-03-20 12:54 UTC, cichan02 commented on src/main/java/by/piskunou/solvdlaba/service/impl/JwtServiceImpl.java
> +    public Mono<String> generateAccessToken(User user) {
Even if I use this in a controller?

@PostMapping("/generate-token/access")
@Operation(summary = "Generate access token")
@Parameter(name = "userDetails", description = "User's details for generating access token")
public Mono<String> generateAccessToken(@RequestBody User user) {
     return jwtService.generateAccessToken(user);
}

2023-03-20 12:56 UTC, h1alexbel commented on src/main/java/by/piskunou/solvdlaba/service/impl/JwtServiceImpl.java
> +    public Mono<String> generateAccessToken(User user) {
@cichan02 yeas, in this case, you just generating a simple string. why do you need Mono?

2023-03-20 14:52 UTC, h1alexbel requested changes
@cichan02 please remove comments

2023-03-20 14:52 UTC, h1alexbel commented on pom.xml
>          <!-- https://mvnrepository.com/artifact/org.springframework.kafka/spring-kafka -->
please remove comments

2023-03-20 14:52 UTC, h1alexbel commented on pom.xml
>          <!-- https://mvnrepository.com/artifact/org.mapstruct/mapstruct -->
remove comments

2023-03-20 14:56 UTC, merged